# Generated by Django 6.0.3 on 2026-09-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_message_source_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('quotation', 'Request a quotation'), ('consultation', 'Book a consultation'), ('demo', 'Request a product demo'), ('sales', 'Contact sales team'), ('general', 'General enquiry')], default='general', max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('interest', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('client_token', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
