# Generated by Django 6.1 on 2026-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeIndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('section', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'chunk_index'],
                'indexes': [models.Index(fields=['source', 'chunk_index'], name='chatbot_kno_source_c566cf_idx')],
            },
        ),
    ]
